language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libsfml-dev

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ..
     - make
     - make test
